version: '3.8'

services:
  web:
    build: .
    ports:
      - "${PORT:-5000}:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_APP=${FLASK_APP:-app.py}
