services:
  web:
    build: .
    ports:
      - "${PORT:-7860}:7860"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - SEARXNG_KEY=${SEARXNG_KEY:-http://localhost:8080}
